#!/usr/bin/env python

import argparse
from queue import Empty
import sys
# import requests

parser = argparse.ArgumentParser(add_help=False, prog="httpc")

#### Global arguments
parser.add_argument("-v", help="Prints the detail of the response such as protocol, status, and headers.", action="store_true")
parser.add_argument("-h", help="Associates headers to HTTP Request with the format 'key:value'.", metavar="KEY:VALUE")
parser.add_argument("-u", help="input URL",  action="store", type=str)

subparsers = parser.add_subparsers(dest="command")

get_parser = subparsers.add_parser("get")
post_parser = subparsers.add_parser("post")
help_parser = subparsers.add_parser("help")

group = post_parser.add_mutually_exclusive_group(required=True)
group.add_argument("-d", help="Associates an inline data to the body HTTP POST request.", action="store", type=str)
group.add_argument("-f", help="Associates the content of a file to the body HTTP POST request.", action="store_true")